# Generated by Django 3.2.15 on 2023-10-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.dish')),
            ],
        ),
    ]
