# Generated by Django 4.2.6 on 2023-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chef", "0003_dish_owner_meal_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name_plural": "dishes"},
        ),
        migrations.AddConstraint(
            model_name="dish",
            constraint=models.UniqueConstraint(
                fields=("title", "owner"), name="unique_dish_title_per_owner"
            ),
        ),
    ]
