# Generated by Django 4.2.6 on 2024-01-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chef", "0006_alter_dish_exclude_from_suggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
